language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - wang-junjian@qq.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install
  - wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin

script:
  - gitbook build
  - gitbook pdf . deep-learning-practice.pdf

after_script:
  - cd _book
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/gouchicao/deep-learning-practice.git # 设置 github 地址
